In [97]:
import os,sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
sns.set()

In [103]:

def train_with_filling(fill_value=0, max_iter=100):
    x_original = np.array([[1, 0, 1], [0, 0, 1]])
    x_missing = np.array(([[fill_value, 1, 0], [fill_value, 1, 0]]))
    x = np.concatenate([x_original, x_missing], axis=0)
    y = np.array([1, 0, 1, 0])
    print("train_data:")
    display(x)
    print("label_data:")
    display(y)

    model = LogisticRegression(solver='liblinear', max_iter=max_iter)
    model.fit(x, y)
    print("model.intercept_:", model.intercept_, ", model.coef_:", model.coef_)
    return model

def run_lr_with_filling_value(fill_value=0):
    model = train_with_filling(fill_value=fill_value, max_iter=1000000)
    return model.predict_proba([
        [1, 0, 1], 
        [0, 0, 1],
        [fill_value, 1, 0], 
        [fill_value, 1, 0],
    ])


### missing value를 0으로 채운다면?

In [104]:
run_lr_with_filling_value(0)

train_data:


array([[1, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0]])

label_data:


array([1, 0, 1, 0])

model.intercept_: [-0.04173375] , model.coef_: [[ 0.4200274   0.0139107  -0.05564445]]


array([[0.42003025, 0.57996975],
       [0.52432533, 0.47567467],
       [0.50695532, 0.49304468],
       [0.50695532, 0.49304468]])

### missing value를 1으로 채운다면?

In [105]:
run_lr_with_filling_value(1)

train_data:


array([[1, 0, 1],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 0]])

label_data:


array([1, 0, 1, 0])

model.intercept_: [-0.10768277] , model.coef_: [[ 0.35946944 -0.0837975  -0.02388527]]


array([[0.44326998, 0.55673002],
       [0.53284465, 0.46715535],
       [0.4581012 , 0.5418988 ],
       [0.4581012 , 0.5418988 ]])

### missing value를 0.5으로 채운다면?

In [107]:
run_lr_with_filling_value(0.5)

train_data:


array([[1. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0.5, 1. , 0. ],
       [0.5, 1. , 0. ]])

label_data:


array([1, 0, 1, 0])

model.intercept_: [-0.08150296] , model.coef_: [[ 0.40845284 -0.04089264 -0.04061031]]


array([[0.42890024, 0.57109976],
       [0.53049044, 0.46950956],
       [0.4795537 , 0.5204463 ],
       [0.4795537 , 0.5204463 ]])

### missing value를 99로 채운다면?

In [108]:
run_lr_with_filling_value(99)

train_data:


array([[ 1,  0,  1],
       [ 0,  0,  1],
       [99,  1,  0],
       [99,  1,  0]])

label_data:


array([1, 0, 1, 0])

model.intercept_: [-0.0038149] , model.coef_: [[ 0.0001917  -0.00505459  0.00123968]]


array([[0.50059588, 0.49940412],
       [0.5006438 , 0.4993562 ],
       [0.49747271, 0.50252729],
       [0.49747271, 0.50252729]])

### missing value를 -1로 채운다면?

In [109]:
run_lr_with_filling_value(-1)

train_data:


array([[ 1,  0,  1],
       [ 0,  0,  1],
       [-1,  1,  0],
       [-1,  1,  0]])

label_data:


array([1, 0, 1, 0])

model.intercept_: [0.03291574] , model.coef_: [[ 0.32829413  0.0982475  -0.06533176]]


array([[0.42656542, 0.57343458],
       [0.50810329, 0.49189671],
       [0.54912374, 0.45087626],
       [0.54912374, 0.45087626]])

In [8]:
import torch

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(in_features=2, out_features=1)
        self.activation = nn.Sigmoid()
        
    def forward(self, x):
        x = self.fc(x)
        x = self.activation(x)
        return x


In [10]:
import torch.optim as optim

Net(
  (fc): Linear(in_features=2, out_features=1, bias=True)
  (activation): Sigmoid()
)
Parameter containing:
tensor([[-0.2977, -0.5740]], requires_grad=True) Parameter containing:
tensor([-0.2817], requires_grad=True)


In [118]:
net = Net()
print(net)
print(net.fc.weight, net.fc.bias)

# weight = net.fc.weight          # Weights in the first convolution layer
# weight
# # Detach and create a numpy copy, do some modifications on it
# weight = weight.detach().numpy()
# weight[0,1] = -0.1
# net.fc.weight = torch.nn.Parameter(torch.from_numpy(weight))

fill_value = 2
input_data = torch.tensor(
    np.array([
        [ 1,  0],
        [ 0,  0],
       [fill_value,  1],
       [fill_value,  1],])).type(torch.float)
labels = torch.tensor([[1.0],[0.0],[1.0],[0.0]])

optimizer = optim.SGD(net.parameters(), lr=0.1)
criterion = nn.BCELoss()

net.train(True)   

Net(
  (fc): Linear(in_features=2, out_features=1, bias=True)
  (activation): Sigmoid()
)
Parameter containing:
tensor([[-0.4012, -0.1320]], requires_grad=True) Parameter containing:
tensor([-0.1413], requires_grad=True)


Net(
  (fc): Linear(in_features=2, out_features=1, bias=True)
  (activation): Sigmoid()
)

In [119]:
 
for i in range(100000):
    # in your training loop:
    optimizer.zero_grad()   # zero the gradient buffers

    out = net(input_data)
    loss = criterion(out, labels)
    loss.backward()
    optimizer.step()    # Does the update
    
    if (i+1) % 50000 == 0:
        print('loss:', loss)
        print(net.fc.weight, net.fc.bias)
        print(out)


loss: tensor(0.3494, grad_fn=<BinaryCrossEntropyBackward0>)
Parameter containing:
tensor([[ 10.3347, -15.3520]], requires_grad=True) Parameter containing:
tensor([-5.3125], requires_grad=True)
tensor([[0.9935],
        [0.0049],
        [0.5012],
        [0.5012]], grad_fn=<SigmoidBackward0>)
loss: tensor(0.3480, grad_fn=<BinaryCrossEntropyBackward0>)
Parameter containing:
tensor([[ 11.7437, -17.4684]], requires_grad=True) Parameter containing:
tensor([-6.0165], requires_grad=True)
tensor([[0.9968],
        [0.0024],
        [0.5006],
        [0.5006]], grad_fn=<SigmoidBackward0>)
