In [1]:
import torch
import os
import sys
sys.path.append('/home/md/Ranger-Deep-Learning-Optimizer/ranger')
import ranger2020
import numpy as np
import pandas as pd
import warnings
import numbers
import torch.utils.data as utils
from sklearn.metrics import roc_curve, roc_auc_score
import glob
from tqdm.notebook import tqdm
from pycm import *
from pathlib import Path
import os
import random
import matplotlib.pyplot as plt
import datetime

print("import done")

random.seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('device:', device)

import done
device: cuda


In [2]:
v1_data_path = f'{os.getcwd()}/../data'
train_files = glob.glob(f'{v1_data_path}/train/*.csv')
test_files = glob.glob(f'{v1_data_path}/test/*.csv')
df_label = pd.read_csv(f'{v1_data_path}/label.csv')

In [3]:
train_files

['/home/md/workspace/Apollo_model_dev/v1/code/../data/train/5119.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/6161.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/5723.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/978.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/4956.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/2608.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/4296.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/1242.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/6551.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/2819.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/1190.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/3761.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/386.csv',
 '/home/md/workspace/Apollo_model_dev/v1/code/../data/train/3275.csv',
 '/home/

In [18]:
def timeparser(time):
    return pd.to_timedelta(str(time) + ':00')

# 날짜 단위 시간을 변경, t_delta 표현
def timedelta_today_figure(timedelta):
    return timedelta.days + (timedelta.seconds / 86400)

def df_to_inputs(df, inputdict, inputs):
    for row_index, value in df.iterrows():
        agg_no = inputdict[value.Parameter]
        inputs[agg_no].append(value.Value)
    return inputs

# desc: [sz, min, max, mean, median, std, var]
# inputs.shape: [D, T]
def normalization(desc, inputs):
    for i in range(desc.shape[0]):
        for j in range(len(inputs[i])):
            inputs[i][j] = (inputs[i][j] - desc[i][3]) / desc[i][5]
    return inputs

In [19]:
# #data loeader랑  GRUD  모델 ,df_to_xmd 구현해보기
# df = pd.read_csv(f"{os.getcwd()}/../Flu_screening_api/mock_data/1.csv", header=0, dtype={'Time':str}, parse_dates=['Time'], date_parser=timeparser)

In [20]:
# # 이 부분이 너무너무 이상하다. split:17, size:70
# def df_to_x_m_d(df, inputdict, size, id_position, split):
#     grouped_data = df.groupby('Time')
#     print("grp_data.ngrps:", grouped_data.ngroups)
    
#     x = np.zeros((len(inputdict), grouped_data.ngroups))
#     masking = np.zeros((len(inputdict), grouped_data.ngroups))
#     delta = np.zeros((split, size))
#     timetable = np.zeros(grouped_data.ngroups)
#     id = 0
    
#     all_x = np.zeros((split, 1))
#     s_dataset = np.zeros((3, split, size))
    
#     if grouped_data.ngroups > size:
#         pre_time = pd.to_timedelta(0)
#         t = 0
#         for row_index, value in df.iterrows():
#             agg_no = inputdict[value.Parameter]
#             if pre_time != value.Time:
#                 pre_time = value.Time
#                 if t+1 < row_index and t+1 < len(timetable):
#                     t += 1
#                 print("")
#                 timetable[t] = timedelta_today_figure(value.Time)
#             x[agg_no, t] = value.Value
#             masking[agg_no, t] = 1
        
#         # 최대한 안비어있는 놈들 위주로 뽑음
#         ran_index = grouped_data.count()
#         ran_index = ran_index.reset_index()
#         ran_index = ran_index.sort_values('Value', ascending=False)
#         ran_index = ran_index[:size]
#         ran_index = ran_index.sort_index()
#         ran_index = np.asarray(ran_index.index.values)
#         ran_index[0] = 0
#         ran_index[size-1] = grouped_data.ngroups-1
        
#         # t=0인 무조건 뽑힘
#         id = x[id_position, 0]
        
#         x = x[:split, :]
#         masking = masking[:split, :]
        
#         x_sample = np.zeros((split, size))
#         m_sample = np.zeros((split, size))
#         time_sample = np.zeros(size)
        
#         t_x_sample = x_sample.T
#         t_marsking = m_sample.T
        
#         t_x = x.T
#         t_m = masking.T
        
#         it = np.nditer(ran_index, flags=['f_index'])
#         while not it.finished:
#             t_x_sample[it.index] = t_x[it[0]]
#             t_marsking[it.index] = t_m[it[0]]
#             time_sample[it.index] = timetable[it[0]]
#             it.iternext()
        
#         x = x_sample
#         masking = m_sample
#         timetable = time_sample
        
#         for index, value in np.ndenumerate(masking):
#             if index[1] == 0:
#                 delta[index[0], index[1]] = 0
#             elif masking[index[0], index[1] - 1] == 0:
#                 delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1] + delta[
#                     index[0], index[1] - 1]
#             else:
#                 delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1]
        
#     else:
#         pre_time = pd.to_timedelta(0)
#         t = 0
#         for row_index, value in df.iterrows():
#             print(row_index)
#             return 0
#             agg_no = inputdict[value.Parameter]
#             if pre_time != value.Time:
#                 pre_time = value.Time
#                 if t+1 < row_index and t+1 < len(timetable):
#                     t += 1
#                     timetable[t] = timedelta_today_figure(value.Time)
#                 x[agg_no, t] = value.Value
#                 masking[agg_no, t] = 1
#         id = x[id_position, 0]
#         x = x[:split, :]
#         masking = masking[:split, :]
        
#         x = np.pad(x, ((0,0), (size-grouped_data.ngroups, 0)), 'constant')
#         masking = np.pad(masking, ((0,0), (size-grouped_data.ngroups, 0)), 'constant')
#         timetable = np.pad(timetable, (size-grouped_data.ngroups, 0), 'constant')
        
#         for index, value in np.ndenumerate(masking):
#             '''
#             index[0] = row, agg
#             index[1] = col, time
#             '''
#             if index[1] == 0:
#                 delta[index[0], index[1]] = 0
#             elif masking[index[0], index[1] - 1] == 0:
#                 delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1] + delta[
#                     index[0], index[1] - 1]
#             else:
#                 delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1]
    
#     all_x = np.concatenate((all_x, x), axis=1)
#     all_x = all_x[:, 1:]
    
#     s_dataset[0] = x
#     s_dataset[1] = masking
#     s_dataset[2] = delta
    
#     return s_dataset, all_x, id

In [21]:
def df_to_x_m_d(df, inputdict, size, id_posistion, split):
    grouped_data = df.groupby('Time')
    # generate input vectors
    x = np.zeros((len(inputdict), grouped_data.ngroups))
    masking = np.zeros((len(inputdict), grouped_data.ngroups))
    delta = np.zeros((split, size))
    timetable = np.zeros(grouped_data.ngroups)
    id = 0

    all_x = np.zeros((split, 1))

    s_dataset = np.zeros((3, split, size))

    if grouped_data.ngroups > size:

        # fill the x and masking vectors
        pre_time = pd.to_timedelta(0)
        t = 0
        for row_index, value in df.iterrows():
            '''
            t = colum, time frame
            agg_no = row, variable
            '''
            # print(value)
            agg_no = inputdict[value.Parameter]
            # same timeline check.
            if pre_time != value.Time:
                pre_time = value.Time
                if t + 1 < row_index and t + 1 < len(timetable):
                    t += 1
                timetable[t] = timedelta_today_figure(value.Time)
                # print(len(timetable), t, agg_no)
            # print('agg_no : {}\t t : {}\t value : {}'.format(agg_no, t, value.Value))
            x[agg_no, t] = value.Value
            masking[agg_no, t] = 1

        '''
        # generate random index array 
        ran_index = np.random.choice(grouped_data.ngroups, size=size, replace=False)
        ran_index.sort()
        ran_index[0] = 0
        ran_index[size-1] = grouped_data.ngroups-1
        '''

        # generate index that has most parameters and first/last one.
        ran_index = grouped_data.count()
        ran_index = ran_index.reset_index()
        ran_index = ran_index.sort_values('Value', ascending=False)
        ran_index = ran_index[:size]
        ran_index = ran_index.sort_index()
        ran_index = np.asarray(ran_index.index.values)
        ran_index[0] = 0
        ran_index[size - 1] = grouped_data.ngroups - 1

        # print(ran_index)

        # take id for outcome comparing
        id = x[id_posistion, 0]

        # remove unnesserly parts(rows)
        x = x[:split, :]
        masking = masking[:split, :]

        # coulme(time) sampling
        x_sample = np.zeros((split, size))
        m_sample = np.zeros((split, size))
        time_sample = np.zeros(size)

        t_x_sample = x_sample.T
        t_marsking = m_sample.T
        # t_time = t_sample.T

        t_x = x.T
        t_m = masking.T
        # t_t = t.T

        it = np.nditer(ran_index, flags=['f_index'])
        while not it.finished:
            # print('it.index = {}, it[0] = {}, ran_index = {}'.format(it.index, it[0], ran_index[it.index]))
            t_x_sample[it.index] = t_x[it[0]]
            t_marsking[it.index] = t_m[it[0]]
            time_sample[it.index] = timetable[it[0]]
            it.iternext()

        x = x_sample
        masking = m_sample
        timetable = time_sample
        '''
        # normalize the X
        nor_x = x/max_input[:, np.newaxis]
        '''
        # fill the delta vectors
        for index, value in np.ndenumerate(masking):
            '''
            index[0] = row, agg
            index[1] = col, time
            '''
            if index[1] == 0:
                delta[index[0], index[1]] = 0
            elif masking[index[0], index[1] - 1] == 0:
                delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1] + delta[
                    index[0], index[1] - 1]
            else:
                delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1]

    else:
        # print(grouped_data.ngroups, size)
        # print(df)
        # fill the x and masking vectors
        pre_time = pd.to_timedelta(0)
        t = 0
        for row_index, value in df.iterrows():
            '''
            t = colum, time frame
            agg_no = row, variable
            '''
            # print(value)
            agg_no = inputdict[value.Parameter]

            # same timeline check.
            if pre_time != value.Time:
                pre_time = value.Time
                if t + 1 < row_index and t + 1 < len(timetable):
                    t += 1
                timetable[t] = timedelta_today_figure(value.Time)
            # print('agg_no : {}\t t : {}\t value : {}'.format(agg_no, t, value.Value))
            x[agg_no, t] = value.Value
            masking[agg_no, t] = 1

        # take id for outcome comparing
        id = x[id_posistion, 0]

        # remove unnesserly parts(rows)
        x = x[:split, :]
        masking = masking[:split, :]

        x = np.pad(x, ((0, 0), (size - grouped_data.ngroups, 0)), 'constant')
        masking = np.pad(masking, ((0, 0), (size - grouped_data.ngroups, 0)), 'constant')
        timetable = np.pad(timetable, (size - grouped_data.ngroups, 0), 'constant')
        '''
        # normalize the X
        nor_x = x/max_input[:, np.newaxis]
        '''
        # fill the delta vectors
        for index, value in np.ndenumerate(masking):
            '''
            index[0] = row, agg
            index[1] = col, time
            '''
            if index[1] == 0:
                delta[index[0], index[1]] = 0
            elif masking[index[0], index[1] - 1] == 0:
                delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1] + delta[
                    index[0], index[1] - 1]
            else:
                delta[index[0], index[1]] = timetable[index[1]] - timetable[index[1] - 1]

    all_x = np.concatenate((all_x, x), axis=1)
    all_x = all_x[:, 1:]

    s_dataset[0] = x
    s_dataset[1] = masking
    s_dataset[2] = delta

    return s_dataset, all_x, id

In [22]:
# episode에 담긴 모든 time_step에 대한 각각 feature 평균
def get_mean(x):
    x_mean = []
    for i in range(x.shape[0]):
        mean = np.mean(x[i])
        x_mean.append(mean)
    return x_mean

def get_median(x):
    x_median = []
    for i in range(x.shape[0]):
        median = np.median(x[i])
        x_median.append(median)
    return x_median

def get_std(x):
    x_std = []
    for i in range(x.shape[0]):
        std = np.std(x[i])
        x_std.append(std)
    return x_std

def get_var(x):
    x_var = []
    for i in range(x.shape[0]):
        var = np.var(x[i])
        x_var.append(var)
    return x_var

In [23]:
# dataset 전체를 가지고 계산한 mean, std로 해서 정규화해주는 과정
def dataset_normalize(dataset, mean, std):
    for i in range(dataset.shape[0]):
        # timestep 전부 빼주려고 사이즈 늘려줌(broadcasting)
        dataset[i][0] = (dataset[i][0] - mean[:, None])
        dataset[i][0] = dataset[i][0] / std[:, None]
    return dataset

# [N, 3, 17, 70]
def normalize_chk(dataset):
    all_x_add = np.zeros((dataset[0][0].shape[0], 1))
    for i in range(dataset.shape[0]):
        all_x_add = np.concatenate((all_x_add, dataset[i][0]), axis=1)
    mean = get_mean(all_x_add)
    median = get_median(all_x_add)
    std = get_std(all_x_add)
    var = get_var(all_x_add)
    
    print('mean')
    print(mean)
    print('median')
    print(median)
    print('std')
    print(std)
    print('var')
    print(var)

    return mean, median, std, var

def df_to_y1(df):
    output = df.values
    output = output[:, 2:]
    return output

In [24]:
class GRUD(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers=1, x_mean=0,
                 bias=True, batch_first=False, bidirectional=False, dropout_type='mloss', dropout=0):
        super(GRUD, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.num_layers = num_layers
        self.zeros = torch.autograd.Variable(torch.zeros(input_size))
        self.x_mean = torch.autograd.Variable(torch.clone(x_mean).detach())
        self.bias = bias
        self.batch_first = batch_first
        self.dropout_type = dropout_type
        self.dropout = dropout
        self.bidirectional = bidirectional
        num_directions = 2 if bidirectional else 1

        if not isinstance(dropout, numbers.Number) or not 0 <= dropout <= 1 or isinstance(dropout, bool):
            raise ValueError("dropout should be a number in range [0, 1] "
                             "representing the probability of an element being "
                             "zeroed")
        if dropout > 0 and num_layers == 1:
            warnings.warn("dropout option adds dropout after all but last "
                          "recurrent layer, so non-zero dropout expects "
                          "num_layers greater than 1, but got dropout={} and "
                          "num_layers={}".format(dropout, num_layers))


        self._all_weights = []

        '''
        w_ih = Parameter(torch.Tensor(gate_size, layer_input_size))
        w_hh = Parameter(torch.Tensor(gate_size, hidden_size))
        b_ih = Parameter(torch.Tensor(gate_size))
        b_hh = Parameter(torch.Tensor(gate_size))
        layer_params = (w_ih, w_hh, b_ih, b_hh)
        '''
        # decay rates gamma
        w_dg_x = torch.nn.Parameter(torch.Tensor(input_size))
        w_dg_h = torch.nn.Parameter(torch.Tensor(hidden_size))

        # z
        w_xz = torch.nn.Parameter(torch.Tensor(input_size))
        w_hz = torch.nn.Parameter(torch.Tensor(hidden_size))
        w_mz = torch.nn.Parameter(torch.Tensor(input_size))

        # r
        w_xr = torch.nn.Parameter(torch.Tensor(input_size))
        w_hr = torch.nn.Parameter(torch.Tensor(hidden_size))
        w_mr = torch.nn.Parameter(torch.Tensor(input_size))

        # h_tilde
        w_xh = torch.nn.Parameter(torch.Tensor(input_size))
        w_hh = torch.nn.Parameter(torch.Tensor(hidden_size))
        w_mh = torch.nn.Parameter(torch.Tensor(input_size))

        # y (output)
        w_hy = torch.nn.Parameter(torch.Tensor(output_size, hidden_size))

        # bias
        b_dg_x = torch.nn.Parameter(torch.Tensor(hidden_size))
        b_dg_h = torch.nn.Parameter(torch.Tensor(hidden_size))
        b_z = torch.nn.Parameter(torch.Tensor(hidden_size))
        b_r = torch.nn.Parameter(torch.Tensor(hidden_size))
        b_h = torch.nn.Parameter(torch.Tensor(hidden_size))
        b_y = torch.nn.Parameter(torch.Tensor(output_size))

        layer_params = (w_dg_x, w_dg_h,
                        w_xz, w_hz, w_mz,
                        w_xr, w_hr, w_mr,
                        w_xh, w_hh, w_mh,
                        w_hy,
                        b_dg_x, b_dg_h, b_z, b_r, b_h, b_y)

        use_gpu = torch.cuda.is_available()
        if use_gpu:
            w_dg_x = w_dg_x.cuda()
            w_dg_h = w_dg_h.cuda()
            w_xz, w_hz, w_mz = w_xz.cuda(), w_hz.cuda(), w_mz.cuda()
            w_xr, w_hr, w_mr = w_xr.cuda(), w_hr.cuda(), w_mr.cuda()
            w_xh, w_hh, w_mh = w_xh.cuda(), w_hh.cuda(), w_mh.cuda()
            w_hy = w_hy.cuda()
            b_dg_x, b_dg_h, b_z, b_r, b_h = b_dg_x.cuda(), b_dg_h.cuda(), b_z.cuda(), b_r.cuda(), b_h.cuda()
            b_y = b_y.cuda()

        param_names = ['weight_dg_x', 'weight_dg_h',
                       'weight_xz', 'weight_hz', 'weight_mz',
                       'weight_xr', 'weight_hr', 'weight_mr',
                       'weight_xh', 'weight_hh', 'weight_mh',
                       'weight_hy']
        if bias:
            param_names += ['bias_dg_x', 'bias_dg_h',
                            'bias_z',
                            'bias_r',
                            'bias_h',
                            'bias_y']

        for name, param in zip(param_names, layer_params):
            setattr(self, name, param)
        self._all_weights.append(param_names)

        self.flatten_parameters()
        self.reset_parameters()

    def flatten_parameters(self):
        """
        Resets parameter data pointer so that they can use faster code paths.
        Right now, this works only if the module is on the GPU and cuDNN is enabled.
        Otherwise, it's a no-op.
        """
        any_param = next(self.parameters()).data
        if not any_param.is_cuda or not torch.backends.cudnn.is_acceptable(any_param):
            return

        # If any parameters alias, we fall back to the slower, copying code path. This is
        # a sufficient check, because overlapping parameter buffers that don't completely
        # alias would break the assumptions of the uniqueness check in
        # Module.named_parameters().
        all_weights = self._flat_weights
        unique_data_ptrs = set(p.data_ptr() for p in all_weights)
        if len(unique_data_ptrs) != len(all_weights):
            return

        with torch.cuda.device_of(any_param):
            import torch.backends.cudnn.rnn as rnn

            # NB: This is a temporary hack while we still don't have Tensor
            # bindings for ATen functions
            with torch.no_grad():
                # NB: this is an INPLACE function on all_weights, that's why the
                # no_grad() is necessary.
                torch._cudnn_rnn_flatten_weight(
                    all_weights, (4 if self.bias else 2),
                    self.input_size, rnn.get_cudnn_mode(self.mode), self.hidden_size, self.num_layers,
                    self.batch_first, bool(self.bidirectional))

    def _apply(self, fn):
        ret = super(GRUD, self)._apply(fn)
        self.flatten_parameters()
        return ret

    def reset_parameters(self):
        stdv = 1.0 / math.sqrt(self.hidden_size)
        for weight in self.parameters():
            torch.nn.init.uniform_(weight, -stdv, stdv)

    def check_forward_args(self, input, hidden, batch_sizes):
        is_input_packed = batch_sizes is not None
        expected_input_dim = 2 if is_input_packed else 3
        if input.dim() != expected_input_dim:
            raise RuntimeError(
                'input must have {} dimensions, got {}'.format(
                    expected_input_dim, input.dim()))
        if self.input_size != input.size(-1):
            raise RuntimeError(
                'input.size(-1) must be equal to input_size. Expected {}, got {}'.format(
                    self.input_size, input.size(-1)))

        if is_input_packed:
            mini_batch = int(batch_sizes[0])
        else:
            mini_batch = input.size(0) if self.batch_first else input.size(1)

        num_directions = 2 if self.bidirectional else 1
        expected_hidden_size = (self.num_layers * num_directions,
                                mini_batch, self.hidden_size)

        def check_hidden_size(hx, expected_hidden_size, msg='Expected hidden size {}, got {}'):
            if tuple(hx.size()) != expected_hidden_size:
                raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))

        if self.mode == 'LSTM':
            check_hidden_size(hidden[0], expected_hidden_size,
                              'Expected hidden[0] size {}, got {}')
            check_hidden_size(hidden[1], expected_hidden_size,
                              'Expected hidden[1] size {}, got {}')
        else:
            check_hidden_size(hidden, expected_hidden_size)

    def extra_repr(self):
        s = '{input_size}, {hidden_size}'
        if self.num_layers != 1:
            s += ', num_layers={num_layers}'
        if self.bias is not True:
            s += ', bias={bias}'
        if self.batch_first is not False:
            s += ', batch_first={batch_first}'
        if self.dropout != 0:
            s += ', dropout={dropout}'
        if self.bidirectional is not False:
            s += ', bidirectional={bidirectional}'
        return s.format(**self.__dict__)

    def __setstate__(self, d):
        super(GRUD, self).__setstate__(d)
        if 'all_weights' in d:
            self._all_weights = d['all_weights']
        if isinstance(self._all_weights[0][0], str):
            return
        num_layers = self.num_layers
        num_directions = 2 if self.bidirectional else 1
        self._all_weights = []

        weights = ['weight_dg_x', 'weight_dg_h',
                   'weight_xz', 'weight_hz', 'weight_mz',
                   'weight_xr', 'weight_hr', 'weight_mr',
                   'weight_xh', 'weight_hh', 'weight_mh',
                   'weight_hy',
                   'bias_dg_x', 'bias_dg_h',
                   'bias_z', 'bias_r', 'bias_h', 'bias_y']

        if self.bias:
            self._all_weights += [weights]
        else:
            self._all_weights += [weights[:2]]

    @property
    def _flat_weights(self):
        return list(self._parameters.values())

    @property
    def all_weights(self):
        return [[getattr(self, weight) for weight in weights] for weights in self._all_weights]

    def forward(self, input):
        # input.size = (3, 33,49) : num_input or num_hidden, num_layer or step
        X = torch.squeeze(input[0])  # .size = (33,49)
        Mask = torch.squeeze(input[1])  # .size = (33,49)
        Delta = torch.squeeze(input[2])  # .size = (33,49)
        Hidden_State = torch.autograd.Variable(torch.zeros(input_size))


        step_size = X.size(1)  # 49
        # print('step size : ', step_size)

        output = None
        h = Hidden_State

        # decay rates gamma
        w_dg_x = getattr(self, 'weight_dg_x')
        w_dg_h = getattr(self, 'weight_dg_h')

        # z
        w_xz = getattr(self, 'weight_xz')
        w_hz = getattr(self, 'weight_hz')
        w_mz = getattr(self, 'weight_mz')

        # r
        w_xr = getattr(self, 'weight_xr')
        w_hr = getattr(self, 'weight_hr')
        w_mr = getattr(self, 'weight_mr')

        # h_tilde
        w_xh = getattr(self, 'weight_xh')
        w_hh = getattr(self, 'weight_hh')
        w_mh = getattr(self, 'weight_mh')

        # bias
        b_dg_x = getattr(self, 'bias_dg_x')
        b_dg_h = getattr(self, 'bias_dg_h')
        b_z = getattr(self, 'bias_z')
        b_r = getattr(self, 'bias_r')
        b_h = getattr(self, 'bias_h')

        for layer in range(num_layers):

            x = torch.squeeze(X[:, layer:layer + 1])
            m = torch.squeeze(Mask[:, layer:layer + 1])
            d = torch.squeeze(Delta[:, layer:layer + 1])

            # (4)
            gamma_x = torch.exp(-torch.max(self.zeros, (w_dg_x * d + b_dg_x)))
            gamma_h = torch.exp(-torch.max(self.zeros, (w_dg_h * d + b_dg_h)))

            # (5)
            x = m * x + (1 - m) * (gamma_x * x + (1 - gamma_x) * self.x_mean)

            # (6)
            if self.dropout == 0:
                h = gamma_h * h

                z = torch.sigmoid((w_xz * x + w_hz * h + w_mz * m + b_z))
                r = torch.sigmoid((w_xr * x + w_hr * h + w_mr * m + b_r))
                h_tilde = torch.tanh((w_xh * x + w_hh * (r * h) + w_mh * m + b_h))

                h = (1 - z) * h + z * h_tilde

            elif self.dropout_type == 'Moon':
                '''
                RNNDROP: a novel dropout for rnn in asr(2015)
                '''
                h = gamma_h * h

                z = torch.sigmoid((w_xz * x + w_hz * h + w_mz * m + b_z))
                r = torch.sigmoid((w_xr * x + w_hr * h + w_mr * m + b_r))

                h_tilde = torch.tanh((w_xh * x + w_hh * (r * h) + w_mh * m + b_h))

                h = (1 - z) * h + z * h_tilde
                dropout = torch.nn.Dropout(p=self.dropout)
                h = dropout(h)

            elif self.dropout_type == 'Gal':
                '''
                A Theoretically grounded application of dropout in recurrent neural networks(2015)
                '''
                dropout = torch.nn.Dropout(p=self.dropout)
                h = dropout(h)

                h = gamma_h * h

                z = torch.sigmoid((w_xz * x + w_hz * h + w_mz * m + b_z))
                r = torch.sigmoid((w_xr * x + w_hr * h + w_mr * m + b_r))
                h_tilde = torch.tanh((w_xh * x + w_hh * (r * h) + w_mh * m + b_h))

                h = (1 - z) * h + z * h_tilde

            elif self.dropout_type == 'mloss':
                '''
                recurrent dropout without memory loss arXiv 1603.05118
                g = h_tilde, p = the probability to not drop a neuron
                '''

                h = gamma_h * h

                z = torch.sigmoid((w_xz * x + w_hz * h + w_mz * m + b_z))
                r = torch.sigmoid((w_xr * x + w_hr * h + w_mr * m + b_r))
                h_tilde = torch.tanh((w_xh * x + w_hh * (r * h) + w_mh * m + b_h))

                dropout = torch.nn.Dropout(p=self.dropout)
                h_tilde = dropout(h_tilde)

                h = (1 - z) * h + z * h_tilde

            else:
                h = gamma_h * h

                z = torch.sigmoid((w_xz * x + w_hz * h + w_mz * m + b_z))
                r = torch.sigmoid((w_xr * x + w_hr * h + w_mr * m + b_r))
                h_tilde = torch.tanh((w_xh * x + w_hh * (r * h) + w_mh * m + b_h))

                h = (1 - z) * h + z * h_tilde

        w_hy = getattr(self, 'weight_hy')
        b_y = getattr(self, 'bias_y')
        if epoch == save_point:
            temp_h_col.append(list(h.detach().numpy()))

        output = torch.matmul(w_hy, h) + b_y
        output = torch.sigmoid(output)


        return output

In [25]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [26]:
def data_dataloader(dataset, outcomes, train_proportion=0.8, dev_proportion=0.2, test_proportion=0.2):
    train_index = int(np.floor(dataset.shape[0] * train_proportion))
    dev_index = int(np.floor(dataset.shape[0] * (train_proportion - dev_proportion)))

    # split dataset to tarin/dev/test set
    train_data, train_label = dataset[:train_index, :, :, :], outcomes[:train_index, :]
    dev_data, dev_label = dataset[dev_index:train_index, :, :, :], outcomes[dev_index:train_index, :]
    test_data, test_label = dataset[train_index:, :, :, :], outcomes[train_index:, :]

    # ndarray to tensor
    train_data, train_label = torch.Tensor(train_data), torch.Tensor(train_label)
    dev_data, dev_label = torch.Tensor(dev_data), torch.Tensor(dev_label)
    test_data, test_label = torch.Tensor(test_data), torch.Tensor(test_label)

    # tensor to dataset
    train_dataset = utils.TensorDataset(train_data, train_label)
    dev_dataset = utils.TensorDataset(dev_data, dev_label)
    test_dataset = utils.TensorDataset(test_data, test_label)

    # dataset to dataloader
    train_dataloader = utils.DataLoader(train_dataset)
    dev_dataloader = utils.DataLoader(dev_dataset)
    test_dataloader = utils.DataLoader(test_dataset)

    print("train_data.shape : {}\t train_label.shape : {}".format(train_data.shape, train_label.shape))
    print("dev_data.shape : {}\t dev_label.shape : {}".format(dev_data.shape, dev_label.shape))
    print("test_data.shape : {}\t test_label.shape : {}".format(test_data.shape, test_label.shape))

    return train_dataloader, dev_dataloader, test_dataloader

In [33]:
folder_date = datetime.datetime.now().strftime('%Y%m%d')
outpath_folder = f'{os.getcwd()}/output/notnormal/{folder_date}'

import itertools
import statistics
if os.path.exists(f'{outpath_folder}/dataset.npy'):
    pass
else:
    input_parent = f'{os.getcwd()}/model_data'
    var_list = []
    shuffler = []
    len_checker = []
    path, dirs, files = next(os.walk(input_parent))
    file_count = len(files)
    print(f"Number of files={file_count}")
    for idx, file in tqdm(enumerate(os.listdir(input_parent))):
        inputpath = f"{input_parent}/{file}"
        shuffler.append(inputpath)
        df = pd.read_csv(inputpath)
        var_list.append(df['Parameter'].unique().tolist())
        len_checker.append(len(df['Time'].unique()))
    print(f"for files, time length mean {statistics.mean(len_checker)}, stdev {statistics.stdev(len_checker)}")
    
    flattened =list(set(itertools.chain(*var_list)))
    var_list_in = [x for x in flattened if x not in ['KCDC_surveillance', 'babyid', 'isFlu','weekNumber']]
    var_list = var_list_in + ['babyid', 'isFlu','weekNumber', 'KCDC_surveillance']
    
    numbering = [x for x in range(len(var_list))]
    inputdict = dict(zip(var_list, numbering))
    print(inputdict)
    inputdict = {
        'age_0to2': 0,
        'gender': 1,
        'dew_point_avg': 2,
        'surveillance': 3,
        'temperature_min': 4,
        'temperature_max': 5,
        'antibiotics': 6,
        'humidity_avg': 7,
        'pressure_avg': 8,
        'reducer': 9,
        'age_2to5': 10,
        'weight': 11,
        'age_5to12': 12,
        'temperature_avg': 13,
        'age_12p': 14,
        'fever': 15,
        'KCDC_surveillance': 16,
        'babyid': 17,
        'isFlu': 18,
        'weekNumber': 19
    }
    print(inputdict)
    if os.path.exists(outpath_folder):
        pass
    else: 
        os.makedirs(outpath_folder)

In [36]:
inputdict = {
    'age_0to2': 0,
    'gender': 1,
    'dew_point_avg': 2,
    'surveillance': 3,
    'temperature_min': 4,
    'temperature_max': 5,
    'antibiotics': 6,
    'humidity_avg': 7,
    'pressure_avg': 8,
    'reducer': 9,
    'age_2to5': 10,
    'weight': 11,
    'age_5to12': 12,
    'temperature_avg': 13,
    'age_12p': 14,
    'fever': 15,
    'KCDC_surveillance': 16,
    'babyid': 17,
    'isFlu': 18,
    'weekNumber': 19
}

In [37]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [28]:
size = 300
id_position = inputdict['babyid']
input_length = inputdict['babyid']
print(id_position)
dataset = np.zeros((1, 3, input_length, size))
print(dataset.shape)
all_x_add = np.zeros((input_length, 1))
inputs = []

for i in range(len(inputdict)):
    t = []
    inputs.append(t)

bad_file = []
bad_file_append = bad_file.append
temp_label = []
list_file_discarded = []

np.random.seed(42)

if os.path.exists(f"{outpath_folder}/dataset.npy"):
    pass
else:
    for file in tqdm(shuffler):
        df = pd.read_csv(file, header=0, dtype={'Time':str}, parse_dates=['Time'], date_parser=timeparser)
        df = df.drop(df.columns[0], axis=1)
        
        if np.isnan(df['Value']).any():
            bad_file_append(file)
            pass
        else:
            inputs = df_to_inputs(df=df, inputdict=inputdict, inputs=inputs)
            temp_id = (float(df.loc[df['Parameter'] == 'babyid', 'Value']))
            temp_check = (float(df.loc[df['Parameter'] == 'isFlu', 'Value']))
#             print(temp_id, temp_check)
            #파일이름
            temp_label.append([os.path.basename(file), temp_id, temp_check])
            
            s_dataset, all_x, id = df_to_x_m_d(df=df, inputdict=inputdict, size=size, id_posistion=id_position, split=input_length)
            dataset = np.concatenate((dataset, s_dataset[np.newaxis, :, :, :]))
            all_x_add = np.concatenate((all_x_add, all_x), axis=1)

16
(1, 3, 16, 70)


  0%|          | 0/6657 [00:00<?, ?it/s]

In [29]:
print(dataset.shape)
print(dataset[0,0,:,40])
print(inputdict)
if os.path.exists(f"{outpath_folder}/dataset.npy"):
    dataset = np.load(f"{outpath_folder}/dataset.npy")
    print('load dataset.npy')
else:
    print(inputs[0][0])
    dataset = dataset[1:, :, :, :]
    
    print(dataset.shape)
    print(dataset[0].shape)
    print("hello")
    
    print(all_x_add.shape)
    all_x_add = all_x_add[:, 1:]
    print(all_x_add[:, 55])

(6658, 3, 16, 70)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
{'age_5to12': 0, 'humidity_avg': 1, 'age_0to2': 2, 'gender': 3, 'weight': 4, 'temperature_min': 5, 'surveillance': 6, 'temperature_max': 7, 'antibiotics': 8, 'fever': 9, 'dew_point_avg': 10, 'pressure_avg': 11, 'temperature_avg': 12, 'age_12p': 13, 'reducer': 14, 'age_2to5': 15, 'babyid': 16, 'isFlu': 17, 'weekNumber': 18, 'KCDC_surveillance': 19}
1.0
(6657, 3, 16, 70)
(3, 16, 70)
hello
(16, 465991)
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.  39.3  0.   0.   0.   0.
  0.   0. ]


In [30]:
df2 = pd.DataFrame(temp_label, columns=['filename', 'babyid', 'isflu'])
df2.to_csv(f'{outpath_folder}/label.csv', header=True, index=False)
print(df2.head(10))
df3 = pd.DataFrame(list_file_discarded, columns=['filename', 'reason'])
df3.to_csv(f'{outpath_folder}/discarded.csv', header=True, index=False)

   filename    babyid  isflu
0  3609.csv  297495.0    1.0
1  6395.csv  224325.0    0.0
2  4150.csv  217374.0    0.0
3  3656.csv  276061.0    1.0
4  2218.csv  184763.0    1.0
5  1076.csv  309572.0    1.0
6  3337.csv  220158.0    0.0
7  4082.csv  104239.0    0.0
8  2258.csv  100343.0    1.0
9  6525.csv  285125.0    1.0


In [31]:
import yaml
print(dataset.shape)
if os.path.exists(f"{outpath_folder}/dataset.npy"):
    pass
else:
    train_proportion = 0.8
    train_index = int(all_x_add.shape[1] * train_proportion)
    train_x = all_x_add[:, :train_index]
    print(train_x.shape)
    # print(train_x[2][:1000])

    x_mean = get_mean(train_x)
    print('x_mean', x_mean, len(x_mean))
    x_std = get_std(train_x)
    print('x_std', x_std, len(x_std))
    x_mean = np.asarray(x_mean)
    print("wow",x_mean.shape)
    x_std = np.asarray(x_std)
    print(x_std.shape)

    # dataset = dataset_normalize(dataset=dataset, mean=x_mean, std=x_std)
    dataset = np.nan_to_num(dataset)
    # nor_mean, nor_median, nor_std, nor_var = normalize_chk(dataset)

#     np.save(f'{outpath_folder}/nor_mean', nor_mean)
#     np.save(f'{outpath_folder}/nor_median', nor_median)
    np.save(f'{outpath_folder}/dataset', dataset)


(6657, 3, 16, 70)
(16, 372792)
x_mean [0.0010595720938217559, 0.7507065602266142, 0.005490997660894011, 0.007111204103092341, 0.24217363838279793, 0.04806701860554948, 0.34110039915019635, 0.1763020665679521, 0.013626901864846885, 10.914305296250992, -0.03436554432498551, 14.438221313762101, 0.10681962059271656, 0.0001716775038090946, 0.4890299958153607, 0.007561857550591214] 16
x_std [0.03253381933926217, 6.487766385161938, 0.07389754126885459, 0.08402758403819847, 14.527082613186352, 1.424306864305219, 3.627019104672928, 2.0162015472136976, 0.11593622993013321, 17.233010719598145, 1.6225347072753733, 119.94379374911354, 1.6294316039911763, 0.013101451470878352, 6.034806133137574, 0.0866295322680192] 16
wow (16,)
(16,)


In [32]:
t_dataset = np.load(f"{outpath_folder}/dataset.npy")
print(t_dataset.shape)
df_label = pd.read_csv(f"{outpath_folder}/label.csv")
print(df_label)
np_label = np.array(df_to_y1(df_label), dtype=int)
print(np_label)
np.save(f"{outpath_folder}/np_label.npy", np_label)
print(np_label.shape)

(6657, 3, 16, 70)
      filename    babyid  isflu
0     3609.csv  297495.0    1.0
1     6395.csv  224325.0    0.0
2     4150.csv  217374.0    0.0
3     3656.csv  276061.0    1.0
4     2218.csv  184763.0    1.0
...        ...       ...    ...
6652  4173.csv  200861.0    0.0
6653   394.csv  312864.0    1.0
6654  2628.csv  242210.0    0.0
6655  6524.csv  221479.0    1.0
6656  2577.csv  320543.0    1.0

[6657 rows x 3 columns]
[[1]
 [0]
 [0]
 ...
 [0]
 [1]
 [1]]
(6657, 1)


In [33]:
t_dataset = np.load(f"{outpath_folder}/dataset.npy")
t_out = np.load(f"{outpath_folder}/np_label.npy")

print(t_dataset.shape)
print(t_out.shape)

(6657, 3, 16, 70)
(6657, 1)


In [39]:
train_dataloader, dev_dataloader, test_dataloader = \
        data_dataloader(t_dataset, t_out,train_proportion=0.8, \
                        dev_proportion=0.2, test_proportion=0.2)

# x_mean = torch.Tensor(np.load(f"{outpath_folder}/nor_mean.npy")).clone().detach()
# x_median = torch.Tensor(np.load(f"{outpath_folder}/nor_median.npy")).clone().detach()
x_mean = torch.zeros(inputdict['babyid'])
print(x_mean)
auc_collector = []
acc_collector = []
lr_collector = []
h_collector = {}
label_collector = []
save_point = 100

import math

input_size = inputdict['babyid']
hidden_size = inputdict['babyid']
output_size = 1
num_layers = 70

train_data.shape : torch.Size([5325, 3, 16, 70])	 train_label.shape : torch.Size([5325, 1])
dev_data.shape : torch.Size([1331, 3, 16, 70])	 dev_label.shape : torch.Size([1331, 1])
test_data.shape : torch.Size([1332, 3, 16, 70])	 test_label.shape : torch.Size([1332, 1])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [40]:
ConfusionMatrix

pycm.pycm_obj.ConfusionMatrix

In [41]:
model = GRUD(input_size=input_size, hidden_size=hidden_size, output_size=output_size, dropout=0, dropout_type='Moon', x_mean=x_mean, num_layers=num_layers)

count = count_parameters(model)
print('number of parameters : ', count)
print(list(model.parameters())[0].grad)

number of parameters :  273
None


In [42]:
designated_epochs = 95
criterion = torch.nn.BCELoss()
optimizer = ranger2020.Ranger(model.parameters(), lr=0.1)
scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=0.01, steps_per_epoch=len(train_dataloader), epochs=designated_epochs)

epoch_losses = []

old_state_dict = {}
for key in model.state_dict():
    old_state_dict[key] = model.state_dict()[key].clone()

Ranger optimizer loaded. 
Gradient Centralization usage = True
GC applied to both conv and fc layers


In [ ]:
for epoch in tqdm(range(designated_epochs)):
    losses, acc = [], []
    label, pred = [], []
    model.train()
    temp_h_col = []
    for train_data, train_label in tqdm(train_dataloader):
        # Zero the parameter gradients
        optimizer.zero_grad()
        train_data = torch.squeeze(train_data)
        train_label = torch.squeeze(train_label).view(-1,1)
        
        # Forward pass : Compute predicted y by passing train data to the model
        y_pred = model(train_data).view(-1, 1)
        
        # Save predict and label
        pred.append(y_pred.item() > 0.5)
        label.append(train_label.item())
        
        # Compute loss
        loss = criterion(y_pred, train_label)
        acc.append(torch.eq((torch.sigmoid(y_pred).data > 0.5).float(), train_label))
        losses.append(loss.item())
        
        # perform a backward pass, and update the weights.
        loss.backward()
        optimizer.step()## due to tpu?
        #xm.optimizer_step(optimizer, barrier=True)
        scheduler.step()
    train_acc = torch.mean(torch.cat(acc).float())
    train_loss = np.mean(losses)

    train_pred_out = pred
    train_label_out = label
    
    ##hidden_state_collect
    h_collector[epoch] = temp_h_col
    #label_collect.append(label)

    # save new params
    new_state_dict = {}
    for key in model.state_dict():
        new_state_dict[key] = model.state_dict()[key].clone()

    # compare params
    for key in old_state_dict:
        if (old_state_dict[key] == new_state_dict[key]).all():
            print('Not updated in {}'.format(key))
                
                
    # dev loss
    losses, acc = [], []
    label, pred = [], []
    model.eval()
    for dev_data, dev_label in tqdm(dev_dataloader):
        # Squeeze the data [1, 33, 49], [1,5] to [33, 49], [5]
        dev_data = torch.squeeze(dev_data)
        dev_label = torch.squeeze(dev_label).view(-1,1)

        # Forward pass : Compute predicted y by passing train data to the model
        y_pred = model(dev_data).view(-1,1)

        # Save predict and label
        pred.append(y_pred.item()) 
        label.append(dev_label.item())

        # Compute loss
        loss = criterion(y_pred, dev_label)
        acc.append(torch.eq((torch.sigmoid(y_pred).data > 0.5).float(), dev_label))
        losses.append(loss.item())

    dev_acc = torch.mean(torch.cat(acc).float())
    dev_loss = np.mean(losses)

    dev_pred_out = pred
    dev_label_out = label

    # test loss
    losses, acc = [], []
    label, pred = [], []
    model.eval()
    for test_data, test_label in tqdm(test_dataloader):
        
        test_data = torch.squeeze(test_data)
        test_label = torch.squeeze(test_label).view(-1,1)
        
        # Forward pass : Compute predicted y by passing train data to the model
        y_pred = model(test_data).view(-1,1)

        # Save predict and label
        pred.append(y_pred.item()) 
        label.append(test_label.item())

        # Compute loss
        #loss = criterion(y_pred, test_label)
        loss = criterion(y_pred, test_label)
        acc.append(torch.eq((torch.sigmoid(y_pred).data > 0.5).float(), test_label))
        losses.append(loss.item())
            

    test_acc = torch.mean(torch.cat(acc).float())
    test_loss = np.mean(losses)

    test_pred_out = pred
    test_label_out = label
    #print(pred, label)

    epoch_losses.append([
        train_loss, dev_loss, test_loss,
        train_acc, dev_acc, test_acc,
        train_pred_out, dev_pred_out, test_pred_out,
        train_label_out, dev_label_out, test_label_out,
    ])

    pred = np.asarray(pred)
    psuedo_pred = [int(round(x)) for x in pred]
    pred_text = ['Flu' if x ==1 else 'Not' for x in psuedo_pred]
    label = np.asarray(label)
    label_text = ['Flu' if int(x) ==1 else 'Not' for x in label]
    auc_score = roc_auc_score(label, pred)
    
    #print(label, psuedo_pred)
    #raise

    print(f"Epoch: {epoch+1} Learning rate: {scheduler.get_last_lr()[0]:.5f}, Train loss: {train_loss:.4f}, Dev loss: {dev_loss:.4f}, Test loss: {test_loss:.4f}, Test AUC: {auc_score:.4f}")
    # save the parameters
    auc_collector.append(auc_score)
    acc_collector.append(test_acc.item())
    lr_collector.append(scheduler.get_last_lr()[0])
    train_log = []
    train_log.append(model.state_dict())
    torch.save(model.state_dict(), f"{outpath_folder}/para_e_{str(epoch+1).zfill(3)}_lr_{scheduler.get_last_lr()[0]}.pt")
    print(label, pred)
    cm = ConfusionMatrix(label_text, pred_text)
    cm.print_matrix()
    print(cm.binary)
    print(cm.ACC, cm.AUC)

  0%|          | 0/95 [00:00<?, ?it/s]

  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 1 Learning rate: 0.00043, Train loss: 0.6959, Dev loss: 0.6889, Test loss: 0.6877, Test AUC: 0.6405
[0. 0. 0. ... 0. 1. 1.] [0.49415725 0.49469906 0.48787701 ... 0.48449984 0.45324248 0.51502395]
Predict   Flu       Not       
Actual
Flu       108       545       

Not       36        643       


True
{'Flu': 0.5638138138138138, 'Not': 0.5638138138138138} {'Flu': 0.5561856797786132, 'Not': 0.5561856797786132}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 2 Learning rate: 0.00052, Train loss: 0.6822, Dev loss: 0.6722, Test loss: 0.6683, Test AUC: 0.7105
[0. 0. 0. ... 0. 1. 1.] [0.51468277 0.51741403 0.45362198 ... 0.4327977  0.35412368 0.54588288]
Predict   Flu       Not       
Actual
Flu       576       77        

Not       413       266       


True
{'Flu': 0.6321321321321322, 'Not': 0.6321321321321322} {'Flu': 0.6369176362861337, 'Not': 0.6369176362861337}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 3 Learning rate: 0.00066, Train loss: 0.6147, Dev loss: 0.5549, Test loss: 0.5356, Test AUC: 0.8453
[0. 0. 0. ... 0. 1. 1.] [0.3201966  0.3768979  0.27424708 ... 0.34065777 0.21578705 0.66838557]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       201       478       


True
{'Flu': 0.7905405405405406, 'Not': 0.7905405405405406} {'Flu': 0.7922638688098659, 'Not': 0.7922638688098659}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 4 Learning rate: 0.00086, Train loss: 0.5250, Dev loss: 0.5184, Test loss: 0.4906, Test AUC: 0.8463
[0. 0. 0. ... 0. 1. 1.] [0.21266529 0.26908466 0.14348458 ... 0.2238778  0.11955411 0.70187223]
Predict   Flu       Not       
Actual
Flu       564       89        

Not       196       483       


True
{'Flu': 0.786036036036036, 'Not': 0.786036036036036} {'Flu': 0.7875230893102414, 'Not': 0.7875230893102414}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 5 Learning rate: 0.00111, Train loss: 0.5040, Dev loss: 0.5085, Test loss: 0.4747, Test AUC: 0.8524
[0. 0. 0. ... 0. 1. 1.] [0.15197633 0.23761247 0.09268226 ... 0.18679111 0.09220181 0.70387644]
Predict   Flu       Not       
Actual
Flu       568       85        

Not       197       482       


True
{'Flu': 0.7882882882882883, 'Not': 0.7882882882882883} {'Flu': 0.7898494994214986, 'Not': 0.7898494994214986}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 6 Learning rate: 0.00141, Train loss: 0.4968, Dev loss: 0.5005, Test loss: 0.4666, Test AUC: 0.8562
[0. 0. 0. ... 0. 1. 1.] [0.0972324  0.63871825 0.08148862 ... 0.25831661 0.10428711 0.68467194]
Predict   Flu       Not       
Actual
Flu       601       52        

Not       234       445       


True
{'Flu': 0.7852852852852853, 'Not': 0.7852852852852853} {'Flu': 0.787871543369562, 'Not': 0.787871543369562}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 7 Learning rate: 0.00176, Train loss: 0.4838, Dev loss: 0.4808, Test loss: 0.4417, Test AUC: 0.8776
[0. 0. 0. ... 0. 1. 1.] [0.06776845 0.49357063 0.06767139 ... 0.20610863 0.08936428 0.73060775]
Predict   Flu       Not       
Actual
Flu       589       64        

Not       197       482       


True
{'Flu': 0.8040540540540541, 'Not': 0.8040540540540541} {'Flu': 0.8059291318870423, 'Not': 0.8059291318870423}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 8 Learning rate: 0.00215, Train loss: 0.4510, Dev loss: 0.4309, Test loss: 0.4010, Test AUC: 0.8949
[0. 0. 0. ... 0. 1. 1.] [0.03927643 0.23828034 0.05518891 ... 0.15055494 0.06986455 0.7299729 ]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       131       548       


True
{'Flu': 0.8468468468468469, 'Not': 0.8468468468468469} {'Flu': 0.8476387444828107, 'Not': 0.8476387444828107}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 9 Learning rate: 0.00257, Train loss: 0.4195, Dev loss: 0.4144, Test loss: 0.3940, Test AUC: 0.8984
[0. 0. 0. ... 0. 1. 1.] [0.03252519 0.14833055 0.06426048 ... 0.15618117 0.07572307 0.70152962]
Predict   Flu       Not       
Actual
Flu       577       76        

Not       138       541       


True
{'Flu': 0.8393393393393394, 'Not': 0.8393393393393394} {'Flu': 0.8401870149553324, 'Not': 0.8401870149553324}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 10 Learning rate: 0.00303, Train loss: 0.4128, Dev loss: 0.4108, Test loss: 0.3987, Test AUC: 0.8967
[0. 0. 0. ... 0. 1. 1.] [0.07532058 0.08907703 0.10826839 ... 0.13966082 0.11102336 0.6078977 ]
Predict   Flu       Not       
Actual
Flu       576       77        

Not       131       548       


True
{'Flu': 0.8438438438438438, 'Not': 0.8438438438438438} {'Flu': 0.8445759573465167, 'Not': 0.8445759573465167}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 11 Learning rate: 0.00352, Train loss: 0.4074, Dev loss: 0.3955, Test loss: 0.3824, Test AUC: 0.9032
[0. 0. 0. ... 0. 1. 1.] [0.04063714 0.09925327 0.09620109 ... 0.15735361 0.0913883  0.5585013 ]
Predict   Flu       Not       
Actual
Flu       571       82        

Not       115       564       


True
{'Flu': 0.8521021021021021, 'Not': 0.8521021021021021} {'Flu': 0.8525295058267384, 'Not': 0.8525295058267384}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 12 Learning rate: 0.00402, Train loss: 0.4018, Dev loss: 0.3896, Test loss: 0.3748, Test AUC: 0.9079
[0. 0. 0. ... 0. 1. 1.] [0.03351316 0.10959714 0.0954389  ... 0.17942867 0.09269983 0.48505983]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       120       559       


True
{'Flu': 0.8513513513513513, 'Not': 0.8513513513513513} {'Flu': 0.8519104078378481, 'Not': 0.8519104078378481}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 13 Learning rate: 0.00454, Train loss: 0.4001, Dev loss: 0.3951, Test loss: 0.3824, Test AUC: 0.9050
[0. 0. 0. ... 0. 1. 1.] [0.03165058 0.10727818 0.09087619 ... 0.18858814 0.08765306 0.50263476]
Predict   Flu       Not       
Actual
Flu       583       70        

Not       138       541       


True
{'Flu': 0.8438438438438438, 'Not': 0.8438438438438438} {'Flu': 0.8447811956597735, 'Not': 0.8447811956597735}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 14 Learning rate: 0.00507, Train loss: 0.4027, Dev loss: 0.3909, Test loss: 0.3789, Test AUC: 0.9067
[0. 0. 0. ... 0. 1. 1.] [0.03231869 0.1051636  0.09611419 ... 0.22803757 0.10906842 0.5075317 ]
Predict   Flu       Not       
Actual
Flu       561       92        

Not       110       569       


True
{'Flu': 0.8483483483483484, 'Not': 0.8483483483483484} {'Flu': 0.8485544231111872, 'Not': 0.8485544231111872}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 15 Learning rate: 0.00560, Train loss: 0.4016, Dev loss: 0.4109, Test loss: 0.3905, Test AUC: 0.8994
[0. 0. 0. ... 0. 1. 1.] [0.03692915 0.20167172 0.04181879 ... 0.135985   0.05677473 0.62329203]
Predict   Flu       Not       
Actual
Flu       572       81        

Not       133       546       


True
{'Flu': 0.8393393393393394, 'Not': 0.8393393393393394} {'Flu': 0.8400404161601491, 'Not': 0.8400404161601491}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 16 Learning rate: 0.00612, Train loss: 0.4058, Dev loss: 0.3941, Test loss: 0.3810, Test AUC: 0.9057
[0. 0. 0. ... 0. 1. 1.] [0.02834367 0.11581789 0.10561465 ... 0.25313497 0.11723444 0.50321746]
Predict   Flu       Not       
Actual
Flu       582       71        

Not       138       541       


True
{'Flu': 0.8430930930930931, 'Not': 0.8430930930930931} {'Flu': 0.8440154988757, 'Not': 0.8440154988757}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 17 Learning rate: 0.00663, Train loss: 0.4024, Dev loss: 0.4119, Test loss: 0.3923, Test AUC: 0.9002
[0. 0. 0. ... 0. 1. 1.] [0.03600717 0.18561037 0.0435385  ... 0.1364101  0.06142168 0.63618457]
Predict   Flu       Not       
Actual
Flu       572       81        

Not       136       543       


True
{'Flu': 0.8370870870870871, 'Not': 0.8370870870870871} {'Flu': 0.8378312850850387, 'Not': 0.8378312850850387}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 18 Learning rate: 0.00713, Train loss: 0.4048, Dev loss: 0.4071, Test loss: 0.3864, Test AUC: 0.9015
[0. 0. 0. ... 0. 1. 1.] [0.03282757 0.18648697 0.04411129 ... 0.13626094 0.06557707 0.67070198]
Predict   Flu       Not       
Actual
Flu       571       82        

Not       128       551       


True
{'Flu': 0.8423423423423423, 'Not': 0.8423423423423423} {'Flu': 0.8429566045012596, 'Not': 0.8429566045012596}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 19 Learning rate: 0.00760, Train loss: 0.4075, Dev loss: 0.3884, Test loss: 0.3736, Test AUC: 0.9104
[0. 0. 0. ... 0. 1. 1.] [0.02404226 0.12059097 0.11160388 ... 0.27191794 0.1527558  0.57804132]
Predict   Flu       Not       
Actual
Flu       561       92        

Not       109       570       


True
{'Flu': 0.8490990990990991, 'Not': 0.8490990990990991} {'Flu': 0.849290800136224, 'Not': 0.849290800136224}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 20 Learning rate: 0.00804, Train loss: 0.3991, Dev loss: 0.3914, Test loss: 0.3752, Test AUC: 0.9111
[0. 0. 0. ... 0. 1. 1.] [0.02356325 0.09845347 0.0862699  ... 0.22607942 0.13535433 0.54879069]
Predict   Flu       Not       
Actual
Flu       571       82        

Not       134       545       


True
{'Flu': 0.8378378378378378, 'Not': 0.8378378378378378} {'Flu': 0.8385383423510387, 'Not': 0.8385383423510387}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 21 Learning rate: 0.00845, Train loss: 0.3995, Dev loss: 0.3816, Test loss: 0.3667, Test AUC: 0.9133
[0. 0. 0. ... 0. 1. 1.] [0.02420936 0.12784608 0.12590471 ... 0.29270923 0.1865463  0.5886026 ]
Predict   Flu       Not       
Actual
Flu       565       88        

Not       110       569       


True
{'Flu': 0.8513513513513513, 'Not': 0.8513513513513513} {'Flu': 0.8516172102474813, 'Not': 0.8516172102474813}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 22 Learning rate: 0.00882, Train loss: 0.3978, Dev loss: 0.3789, Test loss: 0.3624, Test AUC: 0.9171
[0. 0. 0. ... 0. 1. 1.] [0.0231648  0.12199441 0.12132116 ... 0.25271106 0.18260808 0.5934431 ]
Predict   Flu       Not       
Actual
Flu       570       83        

Not       110       569       


True
{'Flu': 0.8551051051051051, 'Not': 0.8551051051051051} {'Flu': 0.8554456941678489, 'Not': 0.8554456941678489}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 23 Learning rate: 0.00914, Train loss: 0.3978, Dev loss: 0.3977, Test loss: 0.3757, Test AUC: 0.9024
[0. 0. 0. ... 0. 1. 1.] [0.03053158 0.17235878 0.05559437 ... 0.13556935 0.1213052  0.71321893]
Predict   Flu       Not       
Actual
Flu       573       80        

Not       109       570       


True
{'Flu': 0.8581081081081081, 'Not': 0.8581081081081081} {'Flu': 0.8584791615451062, 'Not': 0.8584791615451062}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 24 Learning rate: 0.00942, Train loss: 0.3959, Dev loss: 0.3921, Test loss: 0.3709, Test AUC: 0.9106
[0. 0. 0. ... 0. 1. 1.] [0.02717401 0.12429724 0.08174108 ... 0.14583965 0.12699437 0.62586784]
Predict   Flu       Not       
Actual
Flu       571       82        

Not       103       576       


True
{'Flu': 0.8611111111111112, 'Not': 0.8611111111111112} {'Flu': 0.8613660301271802, 'Not': 0.8613660301271802}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 25 Learning rate: 0.00965, Train loss: 0.3904, Dev loss: 0.3754, Test loss: 0.3561, Test AUC: 0.9188
[0. 0. 0. ... 0. 1. 1.] [0.02034962 0.11226354 0.17227368 ... 0.23801135 0.23158114 0.54273152]
Predict   Flu       Not       
Actual
Flu       571       82        

Not       103       576       


True
{'Flu': 0.8611111111111112, 'Not': 0.8611111111111112} {'Flu': 0.8613660301271802, 'Not': 0.8613660301271802}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 26 Learning rate: 0.00982, Train loss: 0.3877, Dev loss: 0.3916, Test loss: 0.3700, Test AUC: 0.9099
[0. 0. 0. ... 0. 1. 1.] [0.02559719 0.12770303 0.07878597 ... 0.12050314 0.1182953  0.65726674]
Predict   Flu       Not       
Actual
Flu       570       83        

Not       98        581       


True
{'Flu': 0.8641141141141141, 'Not': 0.8641141141141141} {'Flu': 0.8642822184682907, 'Not': 0.8642822184682907}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 27 Learning rate: 0.00993, Train loss: 0.3856, Dev loss: 0.3705, Test loss: 0.3527, Test AUC: 0.9195
[0. 0. 0. ... 0. 1. 1.] [0.02205187 0.10494404 0.15883327 ... 0.23589332 0.24799375 0.55391645]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       99        580       


True
{'Flu': 0.8671171171171171, 'Not': 0.8671171171171171} {'Flu': 0.8673743253636214, 'Not': 0.8673743253636214}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 28 Learning rate: 0.00999, Train loss: 0.3825, Dev loss: 0.3900, Test loss: 0.3694, Test AUC: 0.9106
[0. 0. 0. ... 0. 1. 1.] [0.02369013 0.12012815 0.05568719 ... 0.10887787 0.15225826 0.6576522 ]
Predict   Flu       Not       
Actual
Flu       567       86        

Not       105       574       


True
{'Flu': 0.8566066066066066, 'Not': 0.8566066066066066} {'Flu': 0.8568304889408125, 'Not': 0.8568304889408125}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 29 Learning rate: 0.01000, Train loss: 0.3753, Dev loss: 0.3619, Test loss: 0.3486, Test AUC: 0.9218
[0. 0. 0. ... 0. 1. 1.] [0.02057518 0.09517094 0.14646161 ... 0.24699223 0.46475306 0.5570212 ]
Predict   Flu       Not       
Actual
Flu       573       80        

Not       104       575       


True
{'Flu': 0.8618618618618619, 'Not': 0.8618618618618619} {'Flu': 0.8621610466702903, 'Not': 0.8621610466702903}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 30 Learning rate: 0.00999, Train loss: 0.3691, Dev loss: 0.3608, Test loss: 0.3470, Test AUC: 0.9222
[0. 0. 0. ... 0. 1. 1.] [0.01831992 0.08818849 0.12055603 ... 0.21673834 0.47391328 0.55822182]
Predict   Flu       Not       
Actual
Flu       571       82        

Not       103       576       


True
{'Flu': 0.8611111111111112, 'Not': 0.8611111111111112} {'Flu': 0.8613660301271802, 'Not': 0.8613660301271802}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 31 Learning rate: 0.00997, Train loss: 0.3670, Dev loss: 0.3773, Test loss: 0.3590, Test AUC: 0.9152
[0. 0. 0. ... 0. 1. 1.] [0.02255243 0.10923502 0.06723513 ... 0.10679393 0.31336051 0.66342491]
Predict   Flu       Not       
Actual
Flu       565       88        

Not       104       575       


True
{'Flu': 0.8558558558558559, 'Not': 0.8558558558558559} {'Flu': 0.8560354723977022, 'Not': 0.8560354723977022}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 32 Learning rate: 0.00993, Train loss: 0.3652, Dev loss: 0.3766, Test loss: 0.3585, Test AUC: 0.9149
[0. 0. 0. ... 0. 1. 1.] [0.02039243 0.10298625 0.05562356 ... 0.0959232  0.29174465 0.67032897]
Predict   Flu       Not       
Actual
Flu       565       88        

Not       103       576       


True
{'Flu': 0.8566066066066066, 'Not': 0.8566066066066066} {'Flu': 0.856771849422739, 'Not': 0.856771849422739}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 33 Learning rate: 0.00989, Train loss: 0.3623, Dev loss: 0.3730, Test loss: 0.3544, Test AUC: 0.9172
[0. 0. 0. ... 0. 1. 1.] [0.01976002 0.10636824 0.05096735 ... 0.09960869 0.29545686 0.67456996]
Predict   Flu       Not       
Actual
Flu       567       86        

Not       97        582       


True
{'Flu': 0.8626126126126126, 'Not': 0.8626126126126126} {'Flu': 0.862721505141107, 'Not': 0.862721505141107}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 34 Learning rate: 0.00983, Train loss: 0.3597, Dev loss: 0.3702, Test loss: 0.3524, Test AUC: 0.9182
[0. 0. 0. ... 0. 1. 1.] [0.01933351 0.10687783 0.04858885 ... 0.09507333 0.30147356 0.68712896]
Predict   Flu       Not       
Actual
Flu       568       85        

Not       98        581       


True
{'Flu': 0.8626126126126126, 'Not': 0.8626126126126126} {'Flu': 0.8627508249001437, 'Not': 0.8627508249001437}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 35 Learning rate: 0.00977, Train loss: 0.3572, Dev loss: 0.3535, Test loss: 0.3362, Test AUC: 0.9253
[0. 0. 0. ... 0. 1. 1.] [0.01768995 0.09948136 0.07321942 ... 0.16120796 0.43651894 0.68875045]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       99        580       


True
{'Flu': 0.8671171171171171, 'Not': 0.8671171171171171} {'Flu': 0.8673743253636214, 'Not': 0.8673743253636214}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 36 Learning rate: 0.00969, Train loss: 0.3536, Dev loss: 0.3472, Test loss: 0.3310, Test AUC: 0.9280
[0. 0. 0. ... 0. 1. 1.] [0.01548972 0.092577   0.08055241 ... 0.18293588 0.49744859 0.64393002]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       96        583       


True
{'Flu': 0.8716216216216216, 'Not': 0.8716216216216216} {'Flu': 0.8718805467909523, 'Not': 0.8718805467909523}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 37 Learning rate: 0.00960, Train loss: 0.3521, Dev loss: 0.3443, Test loss: 0.3278, Test AUC: 0.9294
[0. 0. 0. ... 0. 1. 1.] [0.01616365 0.09650293 0.0890139  ... 0.20808019 0.5510298  0.66047329]
Predict   Flu       Not       
Actual
Flu       577       76        

Not       95        584       


True
{'Flu': 0.8716216216216216, 'Not': 0.8716216216216216} {'Flu': 0.8718512270319156, 'Not': 0.8718512270319156}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 38 Learning rate: 0.00950, Train loss: 0.3488, Dev loss: 0.3419, Test loss: 0.3264, Test AUC: 0.9295
[0. 0. 0. ... 0. 1. 1.] [0.01481358 0.09110864 0.08909821 ... 0.18262343 0.54391265 0.65383482]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       95        584       


True
{'Flu': 0.8723723723723724, 'Not': 0.8723723723723724} {'Flu': 0.8726169238159892, 'Not': 0.8726169238159892}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 39 Learning rate: 0.00940, Train loss: 0.3459, Dev loss: 0.3387, Test loss: 0.3239, Test AUC: 0.9309
[0. 0. 0. ... 0. 1. 1.] [0.01442074 0.08867659 0.08689377 ... 0.1850411  0.57001454 0.61553812]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       93        586       


True
{'Flu': 0.8738738738738738, 'Not': 0.8738738738738738} {'Flu': 0.8740896778660628, 'Not': 0.8740896778660628}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 40 Learning rate: 0.00928, Train loss: 0.3431, Dev loss: 0.3366, Test loss: 0.3234, Test AUC: 0.9315
[0. 0. 0. ... 0. 1. 1.] [0.01349573 0.0846839  0.07923989 ... 0.18135625 0.60295784 0.53774691]
Predict   Flu       Not       
Actual
Flu       577       76        

Not       92        587       


True
{'Flu': 0.8738738738738738, 'Not': 0.8738738738738738} {'Flu': 0.8740603581070261, 'Not': 0.8740603581070261}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 41 Learning rate: 0.00915, Train loss: 0.3407, Dev loss: 0.3336, Test loss: 0.3228, Test AUC: 0.9326
[0. 0. 0. ... 0. 1. 1.] [0.01320134 0.08281557 0.08826787 ... 0.18320639 0.64768916 0.46802068]
Predict   Flu       Not       
Actual
Flu       573       80        

Not       91        588       


True
{'Flu': 0.8716216216216216, 'Not': 0.8716216216216216} {'Flu': 0.871733947995769, 'Not': 0.871733947995769}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 42 Learning rate: 0.00902, Train loss: 0.3377, Dev loss: 0.3312, Test loss: 0.3213, Test AUC: 0.9330
[0. 0. 0. ... 0. 1. 1.] [0.01193542 0.0799827  0.07102388 ... 0.18301871 0.69926846 0.46414471]
Predict   Flu       Not       
Actual
Flu       574       79        

Not       91        588       


True
{'Flu': 0.8723723723723724, 'Not': 0.8723723723723724} {'Flu': 0.8724996447798424, 'Not': 0.8724996447798424}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 43 Learning rate: 0.00887, Train loss: 0.3349, Dev loss: 0.3285, Test loss: 0.3188, Test AUC: 0.9340
[0. 0. 0. ... 0. 1. 1.] [0.01189629 0.08535253 0.06851879 ... 0.18545119 0.73718548 0.47601825]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       91        588       


True
{'Flu': 0.8731231231231231, 'Not': 0.8731231231231231} {'Flu': 0.873265341563916, 'Not': 0.873265341563916}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 44 Learning rate: 0.00872, Train loss: 0.3325, Dev loss: 0.3269, Test loss: 0.3171, Test AUC: 0.9350
[0. 0. 0. ... 0. 1. 1.] [0.01108202 0.08096173 0.06113286 ... 0.18549667 0.76091272 0.4663648 ]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       90        589       


True
{'Flu': 0.8738738738738738, 'Not': 0.8738738738738738} {'Flu': 0.8740017185889528, 'Not': 0.8740017185889528}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 45 Learning rate: 0.00856, Train loss: 0.3314, Dev loss: 0.3247, Test loss: 0.3144, Test AUC: 0.9363
[0. 0. 0. ... 0. 1. 1.] [0.01095637 0.08384418 0.0603578  ... 0.18806536 0.7816906  0.61314207]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       91        588       


True
{'Flu': 0.8753753753753754, 'Not': 0.8753753753753754} {'Flu': 0.8755624319161365, 'Not': 0.8755624319161365}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 46 Learning rate: 0.00839, Train loss: 0.3297, Dev loss: 0.3237, Test loss: 0.3140, Test AUC: 0.9366
[0. 0. 0. ... 0. 1. 1.] [0.01035801 0.0781222  0.0563364  ... 0.18651105 0.80140901 0.44116339]
Predict   Flu       Not       
Actual
Flu       576       77        

Not       89        590       


True
{'Flu': 0.8753753753753754, 'Not': 0.8753753753753754} {'Flu': 0.8755037923980631, 'Not': 0.8755037923980631}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 47 Learning rate: 0.00821, Train loss: 0.3279, Dev loss: 0.3221, Test loss: 0.3124, Test AUC: 0.9372
[0. 0. 0. ... 0. 1. 1.] [0.01024815 0.08240455 0.05424736 ... 0.1872934  0.81300402 0.45722666]
Predict   Flu       Not       
Actual
Flu       576       77        

Not       89        590       


True
{'Flu': 0.8753753753753754, 'Not': 0.8753753753753754} {'Flu': 0.8755037923980631, 'Not': 0.8755037923980631}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 48 Learning rate: 0.00802, Train loss: 0.3268, Dev loss: 0.3218, Test loss: 0.3117, Test AUC: 0.9374
[0. 0. 0. ... 0. 1. 1.] [0.0101236  0.08010247 0.05092087 ... 0.18242612 0.81447452 0.45971021]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       89        590       


True
{'Flu': 0.8746246246246246, 'Not': 0.8746246246246246} {'Flu': 0.8747380956139896, 'Not': 0.8747380956139896}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 49 Learning rate: 0.00783, Train loss: 0.3275, Dev loss: 0.3213, Test loss: 0.3102, Test AUC: 0.9383
[0. 0. 0. ... 0. 1. 1.] [0.00924192 0.08249688 0.05082954 ... 0.18537104 0.83096135 0.44375947]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       90        589       


True
{'Flu': 0.8761261261261262, 'Not': 0.8761261261261262} {'Flu': 0.8762988089411733, 'Not': 0.8762988089411733}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 50 Learning rate: 0.00764, Train loss: 0.3253, Dev loss: 0.3204, Test loss: 0.3099, Test AUC: 0.9383
[0. 0. 0. ... 0. 1. 1.] [0.00948255 0.07978394 0.04774537 ... 0.18852021 0.83283174 0.45010546]
Predict   Flu       Not       
Actual
Flu       576       77        

Not       89        590       


True
{'Flu': 0.8753753753753754, 'Not': 0.8753753753753754} {'Flu': 0.8755037923980631, 'Not': 0.8755037923980631}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 51 Learning rate: 0.00743, Train loss: 0.3241, Dev loss: 0.3195, Test loss: 0.3092, Test AUC: 0.9384
[0. 0. 0. ... 0. 1. 1.] [0.0096634  0.08244087 0.04664711 ... 0.18977296 0.83726799 0.4522939 ]
Predict   Flu       Not       
Actual
Flu       575       78        

Not       89        590       


True
{'Flu': 0.8746246246246246, 'Not': 0.8746246246246246} {'Flu': 0.8747380956139896, 'Not': 0.8747380956139896}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 52 Learning rate: 0.00722, Train loss: 0.3233, Dev loss: 0.3200, Test loss: 0.3095, Test AUC: 0.9381
[0. 0. 0. ... 0. 1. 1.] [0.00966521 0.07932158 0.04305569 ... 0.18290715 0.83535689 0.45780778]
Predict   Flu       Not       
Actual
Flu       577       76        

Not       89        590       


True
{'Flu': 0.8761261261261262, 'Not': 0.8761261261261262} {'Flu': 0.8762694891821365, 'Not': 0.8762694891821365}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 53 Learning rate: 0.00701, Train loss: 0.3225, Dev loss: 0.3190, Test loss: 0.3087, Test AUC: 0.9384
[0. 0. 0. ... 0. 1. 1.] [0.00976027 0.08288625 0.04263799 ... 0.1870032  0.84375185 0.4639301 ]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       89        590       


True
{'Flu': 0.8768768768768769, 'Not': 0.8768768768768769} {'Flu': 0.8770351859662101, 'Not': 0.8770351859662101}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 54 Learning rate: 0.00679, Train loss: 0.3216, Dev loss: 0.3188, Test loss: 0.3085, Test AUC: 0.9384
[0. 0. 0. ... 0. 1. 1.] [0.00958387 0.0807674  0.04120732 ... 0.18532041 0.84682041 0.46176979]
Predict   Flu       Not       
Actual
Flu       577       76        

Not       89        590       


True
{'Flu': 0.8761261261261262, 'Not': 0.8761261261261262} {'Flu': 0.8762694891821365, 'Not': 0.8762694891821365}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 55 Learning rate: 0.00657, Train loss: 0.3208, Dev loss: 0.3178, Test loss: 0.3076, Test AUC: 0.9387
[0. 0. 0. ... 0. 1. 1.] [0.00968608 0.08271588 0.04067255 ... 0.18831104 0.84851021 0.46549571]
Predict   Flu       Not       
Actual
Flu       579       74        

Not       89        590       


True
{'Flu': 0.8776276276276276, 'Not': 0.8776276276276276} {'Flu': 0.8778008827502837, 'Not': 0.8778008827502837}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 56 Learning rate: 0.00634, Train loss: 0.3200, Dev loss: 0.3179, Test loss: 0.3074, Test AUC: 0.9387
[0. 0. 0. ... 0. 1. 1.] [0.00954341 0.0815159  0.03947109 ... 0.18799528 0.85045236 0.46358368]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       89        590       


True
{'Flu': 0.8768768768768769, 'Not': 0.8768768768768769} {'Flu': 0.8770351859662101, 'Not': 0.8770351859662101}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 57 Learning rate: 0.00611, Train loss: 0.3196, Dev loss: 0.3178, Test loss: 0.3072, Test AUC: 0.9386
[0. 0. 0. ... 0. 1. 1.] [0.00950002 0.08222444 0.03913276 ... 0.1888157  0.85245782 0.4659422 ]
Predict   Flu       Not       
Actual
Flu       579       74        

Not       89        590       


True
{'Flu': 0.8776276276276276, 'Not': 0.8776276276276276} {'Flu': 0.8778008827502837, 'Not': 0.8778008827502837}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 58 Learning rate: 0.00588, Train loss: 0.3189, Dev loss: 0.3170, Test loss: 0.3065, Test AUC: 0.9390
[0. 0. 0. ... 0. 1. 1.] [0.00931824 0.08021744 0.03859046 ... 0.19101295 0.85694695 0.46410814]
Predict   Flu       Not       
Actual
Flu       578       75        

Not       89        590       


True
{'Flu': 0.8768768768768769, 'Not': 0.8768768768768769} {'Flu': 0.8770351859662101, 'Not': 0.8770351859662101}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 59 Learning rate: 0.00565, Train loss: 0.3184, Dev loss: 0.3169, Test loss: 0.3065, Test AUC: 0.9389
[0. 0. 0. ... 0. 1. 1.] [0.00925411 0.07976221 0.03850199 ... 0.18997645 0.85839313 0.46498302]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       89        590       


True
{'Flu': 0.8783783783783784, 'Not': 0.8783783783783784} {'Flu': 0.8785665795343571, 'Not': 0.8785665795343571}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 60 Learning rate: 0.00541, Train loss: 0.3176, Dev loss: 0.3164, Test loss: 0.3060, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00920456 0.07837479 0.03819982 ... 0.19150214 0.86187553 0.46607822]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       90        589       


True
{'Flu': 0.8776276276276276, 'Not': 0.8776276276276276} {'Flu': 0.8778302025093203, 'Not': 0.8778302025093203}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 61 Learning rate: 0.00518, Train loss: 0.3171, Dev loss: 0.3160, Test loss: 0.3058, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00919235 0.07936147 0.03890705 ... 0.19179878 0.86354363 0.46614829]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       90        589       


True
{'Flu': 0.8776276276276276, 'Not': 0.8776276276276276} {'Flu': 0.8778302025093203, 'Not': 0.8778302025093203}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 62 Learning rate: 0.00494, Train loss: 0.3164, Dev loss: 0.3157, Test loss: 0.3056, Test AUC: 0.9393
[0. 0. 0. ... 0. 1. 1.] [0.00912181 0.07897311 0.0389665  ... 0.19237389 0.86686701 0.46347037]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       90        589       


True
{'Flu': 0.8776276276276276, 'Not': 0.8776276276276276} {'Flu': 0.8778302025093203, 'Not': 0.8778302025093203}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 63 Learning rate: 0.00470, Train loss: 0.3160, Dev loss: 0.3155, Test loss: 0.3057, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00913993 0.0795076  0.04076073 ... 0.19230683 0.86960095 0.46560171]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       92        587       


True
{'Flu': 0.8761261261261262, 'Not': 0.8761261261261262} {'Flu': 0.8763574484592467, 'Not': 0.8763574484592467}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 64 Learning rate: 0.00447, Train loss: 0.3154, Dev loss: 0.3150, Test loss: 0.3053, Test AUC: 0.9393
[0. 0. 0. ... 0. 1. 1.] [0.00912458 0.07891316 0.04095807 ... 0.19371459 0.87289971 0.4712368 ]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       91        588       


True
{'Flu': 0.8768768768768769, 'Not': 0.8768768768768769} {'Flu': 0.8770938254842835, 'Not': 0.8770938254842835}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 65 Learning rate: 0.00424, Train loss: 0.3150, Dev loss: 0.3147, Test loss: 0.3053, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00922269 0.08054131 0.04305533 ... 0.19363035 0.87626404 0.47919744]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       91        588       


True
{'Flu': 0.8768768768768769, 'Not': 0.8768768768768769} {'Flu': 0.8770938254842835, 'Not': 0.8770938254842835}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 66 Learning rate: 0.00400, Train loss: 0.3143, Dev loss: 0.3143, Test loss: 0.3050, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00930419 0.08141751 0.04347706 ... 0.19537643 0.88075191 0.48347855]
Predict   Flu       Not       
Actual
Flu       580       73        

Not       90        589       


True
{'Flu': 0.8776276276276276, 'Not': 0.8776276276276276} {'Flu': 0.8778302025093203, 'Not': 0.8778302025093203}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 67 Learning rate: 0.00377, Train loss: 0.3138, Dev loss: 0.3140, Test loss: 0.3051, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00946845 0.08223298 0.04742636 ... 0.19708999 0.8860001  0.48985544]
Predict   Flu       Not       
Actual
Flu       581       72        

Not       89        590       


True
{'Flu': 0.8791291291291291, 'Not': 0.8791291291291291} {'Flu': 0.8793322763184306, 'Not': 0.8793322763184306}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 68 Learning rate: 0.00355, Train loss: 0.3132, Dev loss: 0.3138, Test loss: 0.3050, Test AUC: 0.9393
[0. 0. 0. ... 0. 1. 1.] [0.00947097 0.08271258 0.04928884 ... 0.19776654 0.89029408 0.48921609]
Predict   Flu       Not       
Actual
Flu       582       71        

Not       90        589       


True
{'Flu': 0.8791291291291291, 'Not': 0.8791291291291291} {'Flu': 0.8793615960774673, 'Not': 0.8793615960774673}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 69 Learning rate: 0.00332, Train loss: 0.3129, Dev loss: 0.3137, Test loss: 0.3051, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00954239 0.08222146 0.05341778 ... 0.19915132 0.89478201 0.49350873]
Predict   Flu       Not       
Actual
Flu       584       69        

Not       91        588       


True
{'Flu': 0.8798798798798799, 'Not': 0.8798798798798799} {'Flu': 0.8801566126205775, 'Not': 0.8801566126205775}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 70 Learning rate: 0.00310, Train loss: 0.3123, Dev loss: 0.3135, Test loss: 0.3044, Test AUC: 0.9396
[0. 0. 0. ... 0. 1. 1.] [0.00919518 0.08136214 0.05462396 ... 0.20444509 0.89991385 0.47745216]
Predict   Flu       Not       
Actual
Flu       581       72        

Not       90        589       


True
{'Flu': 0.8783783783783784, 'Not': 0.8783783783783784} {'Flu': 0.8785958992933938, 'Not': 0.8785958992933938}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 71 Learning rate: 0.00288, Train loss: 0.3118, Dev loss: 0.3135, Test loss: 0.3050, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00963296 0.08313339 0.05725088 ... 0.19953759 0.90107191 0.4962014 ]
Predict   Flu       Not       
Actual
Flu       585       68        

Not       92        587       


True
{'Flu': 0.8798798798798799, 'Not': 0.8798798798798799} {'Flu': 0.8801859323796142, 'Not': 0.8801859323796142}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 72 Learning rate: 0.00267, Train loss: 0.3113, Dev loss: 0.3136, Test loss: 0.3051, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00963962 0.08218112 0.05854945 ... 0.20324273 0.90485835 0.49181637]
Predict   Flu       Not       
Actual
Flu       585       68        

Not       92        587       


True
{'Flu': 0.8798798798798799, 'Not': 0.8798798798798799} {'Flu': 0.8801859323796142, 'Not': 0.8801859323796142}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 73 Learning rate: 0.00247, Train loss: 0.3109, Dev loss: 0.3135, Test loss: 0.3049, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00969832 0.08266176 0.06061084 ... 0.20480733 0.90767431 0.49329305]
Predict   Flu       Not       
Actual
Flu       586       67        

Not       92        587       


True
{'Flu': 0.8806306306306306, 'Not': 0.8806306306306306} {'Flu': 0.8809516291636877, 'Not': 0.8809516291636877}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 74 Learning rate: 0.00227, Train loss: 0.3104, Dev loss: 0.3135, Test loss: 0.3049, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00969102 0.08243211 0.06139235 ... 0.20628095 0.91003382 0.50186926]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 75 Learning rate: 0.00207, Train loss: 0.3100, Dev loss: 0.3136, Test loss: 0.3053, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00968415 0.08279306 0.06219388 ... 0.20748909 0.9124884  0.48189875]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 76 Learning rate: 0.00188, Train loss: 0.3096, Dev loss: 0.3136, Test loss: 0.3052, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00965335 0.08215589 0.06275015 ... 0.20816459 0.91443908 0.49023128]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 77 Learning rate: 0.00170, Train loss: 0.3091, Dev loss: 0.3136, Test loss: 0.3049, Test AUC: 0.9393
[0. 0. 0. ... 0. 1. 1.] [0.0096691  0.08203632 0.06339306 ... 0.20778942 0.91575682 0.50545293]
Predict   Flu       Not       
Actual
Flu       589       64        

Not       92        587       


True
{'Flu': 0.8828828828828829, 'Not': 0.8828828828828829} {'Flu': 0.8832487195159082, 'Not': 0.8832487195159082}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 78 Learning rate: 0.00153, Train loss: 0.3088, Dev loss: 0.3137, Test loss: 0.3049, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00966765 0.08159805 0.06465359 ... 0.20780967 0.9171167  0.50239462]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 79 Learning rate: 0.00136, Train loss: 0.3084, Dev loss: 0.3137, Test loss: 0.3049, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.00966607 0.08129654 0.06544665 ... 0.2073646  0.91784745 0.50511622]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 80 Learning rate: 0.00120, Train loss: 0.3081, Dev loss: 0.3137, Test loss: 0.3050, Test AUC: 0.9392
[0. 0. 0. ... 0. 1. 1.] [0.0096441  0.08103789 0.06648298 ... 0.20685251 0.91874391 0.503932  ]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 81 Learning rate: 0.00105, Train loss: 0.3078, Dev loss: 0.3137, Test loss: 0.3050, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00960814 0.08095853 0.06720021 ... 0.20667312 0.91953695 0.5034098 ]
Predict   Flu       Not       
Actual
Flu       588       65        

Not       92        587       


True
{'Flu': 0.8821321321321322, 'Not': 0.8821321321321322} {'Flu': 0.8824830227318348, 'Not': 0.8824830227318348}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 82 Learning rate: 0.00091, Train loss: 0.3075, Dev loss: 0.3138, Test loss: 0.3052, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00958071 0.08067607 0.06808633 ... 0.20676284 0.92051548 0.4972485 ]
Predict   Flu       Not       
Actual
Flu       587       66        

Not       92        587       


True
{'Flu': 0.8813813813813813, 'Not': 0.8813813813813813} {'Flu': 0.8817173259477613, 'Not': 0.8817173259477613}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 83 Learning rate: 0.00078, Train loss: 0.3072, Dev loss: 0.3139, Test loss: 0.3054, Test AUC: 0.9391
[0. 0. 0. ... 0. 1. 1.] [0.00956344 0.08036205 0.06883904 ... 0.20707557 0.92137146 0.49297422]
Predict   Flu       Not       
Actual
Flu       587       66        

Not       93        586       


True
{'Flu': 0.8806306306306306, 'Not': 0.8806306306306306} {'Flu': 0.8809809489227245, 'Not': 0.8809809489227245}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 84 Learning rate: 0.00066, Train loss: 0.3069, Dev loss: 0.3140, Test loss: 0.3055, Test AUC: 0.9390
[0. 0. 0. ... 0. 1. 1.] [0.0095613  0.08029952 0.06975868 ... 0.20760103 0.9223749  0.49061203]
Predict   Flu       Not       
Actual
Flu       587       66        

Not       93        586       


True
{'Flu': 0.8806306306306306, 'Not': 0.8806306306306306} {'Flu': 0.8809809489227245, 'Not': 0.8809809489227245}


  0%|          | 0/5325 [00:00<?, ?it/s]

Not updated in weight_dg_x
Not updated in bias_dg_x


  0%|          | 0/1331 [00:00<?, ?it/s]

  0%|          | 0/1332 [00:00<?, ?it/s]

Epoch: 85 Learning rate: 0.00055, Train loss: 0.3067, Dev loss: 0.3141, Test loss: 0.3055, Test AUC: 0.9390
[0. 0. 0. ... 0. 1. 1.] [0.0095741  0.08041628 0.07069675 ... 0.20833574 0.92334378 0.49108386]
Predict   Flu       Not       
Actual
Flu       587       66        

Not       93        586       


True
{'Flu': 0.8806306306306306, 'Not': 0.8806306306306306} {'Flu': 0.8809809489227245, 'Not': 0.8809809489227245}


  0%|          | 0/5325 [00:00<?, ?it/s]